version: '3.8'

services:
  ide:
    image: node:16.5
    volumes:
      - ${PWD}:/app
    working_dir: /app
    command: npm run dev
    environment:
      - BUILD_SERVER_HOST=${TBD}
      - BUILD_SERVER_PORT=${TBD}
    ports:
      - 3000:3000
    networks:
      - public

networks:
  public:
  private: