name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and publish the PRODUCTION Docker image
        run: |
          docker build \
            -t "ghcr.io/bd250227/ncx-ide:${SHORT_SHA}" \
            -t ghcr.io/bd250227/ncx-ide:latest \
            .
          docker push "ghcr.io/bd250227/ncx-ide:${SHORT_SHA}"
          docker push ghcr.io/bd250227/ncx-ide:latest
