name: Pull Request Against Master

on:
  pull_request:
    branches: [master]

jobs:
  production-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the PRODUCTION Docker image
        run: |
          docker build .
  local-dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish the PRODUCTION Docker image
        run: docker-compose build ide
